### ISSUE TITLE
[Bug] JPA Repository 생성 중 발생한 이슈  

### ISSUE THREAD

**Issue by geonuu09** [TransferStay-sbackjung/TransferStay#9]
![image](https://github.com/user-attachments/assets/6a13e08c-5a76-4863-9a99-daee032bf37b)

- JPA 생성 중 아래 에러 코드와 같이 나타납니다. 해결방법을 아시는 분이 계실까요?
- Error : 'com.sbackjung.transferstay.domain.AssignmentPost' has no identifier (every '@Entity' class must declare or inherit at least one '@Id' or '@EmbeddedId' property

**Comment by muunioi** [comment]
AssignmentPost 엔티티에서 Id 어노테이션 사용을 위해 import 한 구문이 잘못되었던 것 같습니다! 관련 내용은 Fix commit에 기술해놓았습니다!
